/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.inventory.ui.navigation

import com.example.inventory.R

/**
 * Interface to describe the navigation destinations for the app.
 * This interface defines the structure for all navigation destinations by providing
 * a common set of properties that each destination must implement.
 */
interface NavigationDestination {
    /**
     * Unique name to define the path for a composable.
     * This is used as the route in the navigation graph to identify the composable that should
     * be displayed when navigating to this destination.
     */
    val route: String

    /**
     * String resource id that contains the title to be displayed for the screen.
     * This ID refers to a resource in the R class, which is generated by Android to allow
     * access to resources, such as strings, drawable images, and layouts.
     */
    val titleRes: Int
}

/**
 * Object that implements the NavigationDestination interface for the home screen of the app.
 * It specifies the navigation route and title for the home destination using constants defined
 * in the resources file (R.string.app_name).
 */
object HomeDestination : NavigationDestination {
    override val route = "home"  // The route name used in the navigation graph for the home screen
    override val titleRes = R.string.app_name  // The resource ID of the string to be used as the title
}
